version: 1.1
workflows:
   - name: "donor_assign"
     subclass: WDL
     primaryDescriptorPath: donor_assignment/donor_assignment.wdl
     filters: 
        branches: 
          - main
        tags: 
          - /.*/
