version: 1.2
workflows:
   - name: "donor_assign"
     subclass: WDL
     primaryDescriptorPath: /donor_assignment/donor_assignment.wdl
     filters:
        branches:
          - main
          - bram-dev
          - bgzblocks
          - split_likelihood_cbcs
        tags:
          - /.*/
   - name: "cisvar"
     subclass: WDL
     primaryDescriptorPath: /cisvar/cisvar.wdl
     filters:
        branches:
          - main
          - bram-dev
        tags:
          - /.*/
